phpab 1.27.1 - Copyright (C) 2009 - 2022 by Arne Blankerts and Contributors

Scanning directory ../

<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'clientapi' => '/api/classes/ClientAPI.php',
                'clientdaomysql' => '/CONTROLLER/dao/ClientDAOMySQL.php',
                'clientdaoredis' => '/CONTROLLER/dao/ClientDAORedis.php',
                'clientdto' => '/MODEL/dto/ClientDTO.php',
                'clientservice' => '/SERVICE/ClientService.php',
                'clientserviceunittest' => '/UnitTests/ClientServiceTest.php',
                'clienttablecreator' => '/START/ClientTableCreator.php',
                'countryapi' => '/api/classes/CountryAPI.php',
                'countrydaomysql' => '/CONTROLLER/dao/CountryDAOMySQL.php',
                'countrydaoredis' => '/CONTROLLER/dao/CountryDAORedis.php',
                'countrydto' => '/MODEL/dto/CountryDTO.php',
                'countryservice' => '/SERVICE/CountryService.php',
                'countrytablecreator' => '/START/CountryTableCreator.php',
                'creator' => '/START/Creator.php',
                'factoryclient' => '/factory/FactoryClient.php',
                'factorycountry' => '/factory/FactoryCountry.php',
                'iclientdto' => '/MODEL/dto/interface/IClientDTO.php',
                'icountrydto' => '/MODEL/dto/interface/ICountryDTO.php',
                'icreator' => '/START/ICreator.php',
                'ientitycruddao' => '/CONTROLLER/IEntityCRUDDao.php',
                'requestparser' => '/utils/RequestParser.php',
                'unittestfactoryclienttest' => '/UnitTests/FactoryClientTest copy.php',
                'unittestfactorycountrytest' => '/UnitTests/FactoryCountryTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd


